version: '3.3'
services:
    db:
        container_name: 'postgresql_db'
        image: postgres
        restart: always
        ports:
            - 5432:5432
        environment:
            - POSTGRES_USER=${DB_USER}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
            - POSTGRES_DB=${DB_NAME}
        command: ["postgres", "-c", "log_statement=all"]
    pgadmin:
        container_name: pgadmin
        image: dpage/pgadmin4
        environment:
            - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
            - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
        ports:
            - 5050:80
        depends_on:
            - db
    
    app:
        container_name: app
        build: .
        volumes:
            - .:/app
        ports:
            - 80:80
        depends_on:
            - db
        restart: always
    redis:
        container_name: redis
        image: redis:6.2-alpine

    celery_worker:
        container_name: celery_worker
        build: .
        command: celery -A core.celery_worker.celery worker --loglevel=info
        volumes:
        - .:/app
        environment:
        - CELERY_BROKER_URL=${CELERY_BROKER_URL}
        - CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND}
        depends_on:
        - app
        - redis

    flower:
        container_name: flower
        build: .
        command: celery -A core.celery_worker.celery flower --port=5555
        ports:
        - 5556:5555
        environment:
        - CELERY_BROKER_URL=${CELERY_BROKER_URL}
        - CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND}
        depends_on:
        - app
        - redis
        - celery_worker
