/*
 * Generated by Digital. Don't modify this file!
 * Any changes will be lost if this file is regenerated.
 */

module labAssignment (
  input D1,
  input D0,
  output G,
  output F,
  output E,
  output D,
  output C,
  output B,
  output A,
  output [7:0] AN
);
  wire A_temp;
  wire s0;
  wire s1;
  wire s2;
  assign AN[0] = 1'b0;
  assign AN[1] = 1'b1;
  assign AN[2] = 1'b1;
  assign AN[3] = 1'b1;
  assign AN[4] = 1'b1;
  assign AN[5] = 1'b1;
  assign AN[6] = 1'b1;
  assign AN[7] = 1'b1;
  assign s0 = ~ D1;
  assign s1 = ~ D0;
  assign G = ~ (D1 | D0);
  assign F = ~ (D0 & D1);
  assign s2 = (D0 & s0);
  assign C = ~ ((s1 & s0) | D1);
  assign B = (s1 & ~ s1);
  assign A_temp = ~ (s2 | (s1 & D1));
  assign E = ~ s2;
  assign D = A_temp;
  assign A = A_temp;
endmodule
