"""fix order table

Revision ID: 1a7d74167e9e
Revises: e1a1fbbc5d32
Create Date: 2022-06-02 22:52:37.190009

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1a7d74167e9e'
down_revision = 'e1a1fbbc5d32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orderitem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('order_status', sa.Enum('PROCESSING', 'INTRANSIT', 'DELIVERED', name='orderstatusenum'), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orderitem_id'), 'orderitem', ['id'], unique=False)
    op.drop_constraint('order_product_id_fkey', 'order', type_='foreignkey')
    op.drop_column('order', 'order_status')
    op.drop_column('order', 'product_id')
    op.drop_column('order', 'quantity')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('order', sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('order', sa.Column('order_status', postgresql.ENUM('PROCESSING', 'INTRANSIT', 'DELIVERED', name='orderstatus'), autoincrement=False, nullable=True))
    op.create_foreign_key('order_product_id_fkey', 'order', 'product', ['product_id'], ['id'])
    op.drop_index(op.f('ix_orderitem_id'), table_name='orderitem')
    op.drop_table('orderitem')
    # ### end Alembic commands ###
