"""refund status is added

Revision ID: 23c0ab93e615
Revises: 89ac3171eb60
Create Date: 2022-06-06 03:14:25.457502

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23c0ab93e615'
down_revision = '89ac3171eb60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("COMMIT")
    op.execute("ALTER TYPE OrderStatusEnum ADD VALUE 'REFUNDED'")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
