"""price_column_for_orderitem

Revision ID: 279ef40ca7cc
Revises: 23c0ab93e615
Create Date: 2022-06-23 17:04:18.469187

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '279ef40ca7cc'
down_revision = '23c0ab93e615'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orderitem', sa.Column('price', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orderitem', 'price')
    # ### end Alembic commands ###
