"""refundorder model is added

Revision ID: 89ac3171eb60
Revises: 1a7d74167e9e
Create Date: 2022-06-06 02:11:10.186563

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89ac3171eb60'
down_revision = '1a7d74167e9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('refundorder',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('orderitem_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['orderitem_id'], ['orderitem.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refundorder_id'), 'refundorder', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_refundorder_id'), table_name='refundorder')
    op.drop_table('refundorder')
    # ### end Alembic commands ###
