"""discount field

Revision ID: e1a1fbbc5d32
Revises: 334605b47eb9
Create Date: 2022-06-02 20:46:12.802925

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1a1fbbc5d32'
down_revision = '334605b47eb9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('discount', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'discount')
    # ### end Alembic commands ###
